package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations will be copied through when generating and any unknown code
// will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"

	"github.com/magendooro/magento2-customer-graphql-go/graph/model"
	"github.com/magendooro/magento2-customer-graphql-go/internal/middleware"
)

// GenerateCustomerToken is the resolver for the generateCustomerToken field.
func (r *mutationResolver) GenerateCustomerToken(ctx context.Context, email string, password string) (*model.CustomerToken, error) {
	return r.CustomerService.GenerateToken(ctx, email, password)
}

// RevokeCustomerToken is the resolver for the revokeCustomerToken field.
func (r *mutationResolver) RevokeCustomerToken(ctx context.Context) (*model.RevokeCustomerTokenOutput, error) {
	// Invalidate the token in the auth middleware cache
	if token := middleware.GetBearerToken(ctx); token != "" && r.TokenResolver != nil {
		r.TokenResolver.Invalidate(token)
	}
	return r.CustomerService.RevokeToken(ctx)
}

// CreateCustomerV2 is the resolver for the createCustomerV2 field.
func (r *mutationResolver) CreateCustomerV2(ctx context.Context, input model.CustomerCreateInput) (*model.CustomerOutput, error) {
	return r.CustomerService.CreateCustomer(ctx, input)
}

// UpdateCustomerV2 is the resolver for the updateCustomerV2 field.
func (r *mutationResolver) UpdateCustomerV2(ctx context.Context, input model.CustomerUpdateInput) (*model.CustomerOutput, error) {
	return r.CustomerService.UpdateCustomer(ctx, input)
}

// ChangeCustomerPassword is the resolver for the changeCustomerPassword field.
func (r *mutationResolver) ChangeCustomerPassword(ctx context.Context, currentPassword string, newPassword string) (*model.Customer, error) {
	return r.CustomerService.ChangePassword(ctx, currentPassword, newPassword)
}

// UpdateCustomerEmail is the resolver for the updateCustomerEmail field.
func (r *mutationResolver) UpdateCustomerEmail(ctx context.Context, email string, password string) (*model.CustomerOutput, error) {
	return r.CustomerService.UpdateEmail(ctx, email, password)
}

// CreateCustomerAddress is the resolver for the createCustomerAddress field.
func (r *mutationResolver) CreateCustomerAddress(ctx context.Context, input model.CustomerAddressInput) (*model.CustomerAddress, error) {
	return r.CustomerService.CreateAddress(ctx, input)
}

// UpdateCustomerAddress is the resolver for the updateCustomerAddress field.
func (r *mutationResolver) UpdateCustomerAddress(ctx context.Context, id int, input model.CustomerAddressInput) (*model.CustomerAddress, error) {
	return r.CustomerService.UpdateAddress(ctx, id, input)
}

// DeleteCustomerAddress is the resolver for the deleteCustomerAddress field.
func (r *mutationResolver) DeleteCustomerAddress(ctx context.Context, id int) (*bool, error) {
	result, err := r.CustomerService.DeleteAddress(ctx, id)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Customer is the resolver for the customer field.
func (r *queryResolver) Customer(ctx context.Context) (*model.Customer, error) {
	return r.CustomerService.GetCustomer(ctx)
}

// IsEmailAvailable is the resolver for the isEmailAvailable field.
func (r *queryResolver) IsEmailAvailable(ctx context.Context, email string) (*model.IsEmailAvailableOutput, error) {
	return r.CustomerService.IsEmailAvailable(ctx, email)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

