package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88-dev

import (
	"context"
	"fmt"
	"strconv"

	"github.com/magendooro/magento2-customer-graphql-go/graph/model"
	"github.com/magendooro/magento2-go-common/middleware"
)

// Orders is the resolver for the orders field on Customer.
func (r *customerResolver) Orders(ctx context.Context, obj *model.Customer, filter *model.CustomerOrdersFilterInput, currentPage *int, pageSize *int, sort *model.CustomerOrderSortInput) (*model.CustomerOrders, error) {
	customerID, err := strconv.Atoi(obj.ID)
	if err != nil {
		return nil, fmt.Errorf("invalid customer id: %w", err)
	}
	page := 1
	if currentPage != nil {
		page = *currentPage
	}
	size := 20
	if pageSize != nil {
		size = *pageSize
	}
	return r.OrderService.GetOrders(ctx, customerID, filter, sort, page, size)
}

// CustomAttributes is the resolver for the custom_attributes field.
func (r *customerResolver) CustomAttributes(ctx context.Context, obj *model.Customer, attributeCodes []string) ([]model.AttributeValueInterface, error) {
	customerID, err := strconv.Atoi(obj.ID)
	if err != nil {
		return nil, nil
	}
	return r.CustomerService.GetCustomAttributes(ctx, "customer", customerID, attributeCodes)
}

// Wishlist is the resolver for the wishlist field.
func (r *customerResolver) Wishlist(ctx context.Context, obj *model.Customer) (*model.Wishlist, error) {
	customerID, err := strconv.Atoi(obj.ID)
	if err != nil {
		return nil, fmt.Errorf("invalid customer id: %w", err)
	}
	wishlistID, err := r.WishlistRepository.GetOrCreate(ctx, customerID)
	if err != nil {
		return nil, err
	}
	count, err := r.WishlistRepository.CountItems(ctx, wishlistID)
	if err != nil {
		return nil, err
	}
	return &model.Wishlist{ID: strconv.Itoa(wishlistID), ItemsCount: count}, nil
}

// CustomAttributesV2 is the resolver for the custom_attributesV2 field.
func (r *customerAddressResolver) CustomAttributesV2(ctx context.Context, obj *model.CustomerAddress, attributeCodes []string) ([]model.AttributeValueInterface, error) {
	if obj.ID == nil {
		return []model.AttributeValueInterface{}, nil
	}
	return r.CustomerService.GetCustomAttributes(ctx, "customer_address", *obj.ID, attributeCodes)
}

// GenerateCustomerToken is the resolver for the generateCustomerToken field.
func (r *mutationResolver) GenerateCustomerToken(ctx context.Context, email string, password string) (*model.CustomerToken, error) {
	return r.CustomerService.GenerateToken(ctx, email, password)
}

// RevokeCustomerToken is the resolver for the revokeCustomerToken field.
func (r *mutationResolver) RevokeCustomerToken(ctx context.Context) (*model.RevokeCustomerTokenOutput, error) {
	return r.CustomerService.RevokeToken(ctx)
}

// CreateCustomerV2 is the resolver for the createCustomerV2 field.
func (r *mutationResolver) CreateCustomerV2(ctx context.Context, input model.CustomerCreateInput) (*model.CustomerOutput, error) {
	return r.CustomerService.CreateCustomer(ctx, input)
}

// UpdateCustomerV2 is the resolver for the updateCustomerV2 field.
func (r *mutationResolver) UpdateCustomerV2(ctx context.Context, input model.CustomerUpdateInput) (*model.CustomerOutput, error) {
	return r.CustomerService.UpdateCustomer(ctx, input)
}

// ChangeCustomerPassword is the resolver for the changeCustomerPassword field.
func (r *mutationResolver) ChangeCustomerPassword(ctx context.Context, currentPassword string, newPassword string) (*model.Customer, error) {
	return r.CustomerService.ChangePassword(ctx, currentPassword, newPassword)
}

// UpdateCustomerEmail is the resolver for the updateCustomerEmail field.
func (r *mutationResolver) UpdateCustomerEmail(ctx context.Context, email string, password string) (*model.CustomerOutput, error) {
	return r.CustomerService.UpdateEmail(ctx, email, password)
}

// CreateCustomerAddress is the resolver for the createCustomerAddress field.
func (r *mutationResolver) CreateCustomerAddress(ctx context.Context, input model.CustomerAddressInput) (*model.CustomerAddress, error) {
	return r.CustomerService.CreateAddress(ctx, input)
}

// UpdateCustomerAddress is the resolver for the updateCustomerAddress field.
func (r *mutationResolver) UpdateCustomerAddress(ctx context.Context, id int, input model.CustomerAddressInput) (*model.CustomerAddress, error) {
	return r.CustomerService.UpdateAddress(ctx, id, input)
}

// DeleteCustomerAddress is the resolver for the deleteCustomerAddress field.
func (r *mutationResolver) DeleteCustomerAddress(ctx context.Context, id int) (*bool, error) {
	result, err := r.CustomerService.DeleteAddress(ctx, id)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateCustomerAddressV2 is the resolver for the updateCustomerAddressV2 field.
func (r *mutationResolver) UpdateCustomerAddressV2(ctx context.Context, uid string, input model.CustomerAddressInput) (*model.CustomerAddress, error) {
	id, err := decodeUID(uid)
	if err != nil {
		return nil, fmt.Errorf("invalid address uid: %w", err)
	}
	return r.CustomerService.UpdateAddress(ctx, id, input)
}

// DeleteCustomerAddressV2 is the resolver for the deleteCustomerAddressV2 field.
func (r *mutationResolver) DeleteCustomerAddressV2(ctx context.Context, uid string) (*bool, error) {
	id, err := decodeUID(uid)
	if err != nil {
		return nil, fmt.Errorf("invalid address uid: %w", err)
	}
	result, err := r.CustomerService.DeleteAddress(ctx, id)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteCustomer is the resolver for the deleteCustomer field.
func (r *mutationResolver) DeleteCustomer(ctx context.Context) (*bool, error) {
	result, err := r.CustomerService.DeleteCustomer(ctx)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// RequestPasswordResetEmail is the resolver for the requestPasswordResetEmail field.
func (r *mutationResolver) RequestPasswordResetEmail(ctx context.Context, email string) (*bool, error) {
	result, err := r.CustomerService.RequestPasswordResetEmail(ctx, email)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// ResetPassword is the resolver for the resetPassword field.
func (r *mutationResolver) ResetPassword(ctx context.Context, email string, resetPasswordToken string, newPassword string) (*bool, error) {
	result, err := r.CustomerService.ResetPassword(ctx, email, resetPasswordToken, newPassword)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// AddProductsToWishlist is the resolver for the addProductsToWishlist field.
func (r *mutationResolver) AddProductsToWishlist(ctx context.Context, wishlistID string, wishlistItems []*model.WishlistItemInput) (*model.AddProductsToWishlistOutput, error) {
	customerID := middleware.GetCustomerID(ctx)
	if customerID == 0 {
		return nil, fmt.Errorf("The current customer isn't authorized.")
	}
	ownWishlistID, err := r.WishlistRepository.GetOrCreate(ctx, customerID)
	if err != nil {
		return nil, err
	}
	// Validate ownership: the wishlistID in the mutation must match the customer's wishlist.
	if wishlistID != strconv.Itoa(ownWishlistID) {
		return nil, fmt.Errorf("The current customer isn't authorized.")
	}
	storeID := middleware.GetStoreID(ctx)

	var userErrors []*model.WishlistUserInputError
	for _, item := range wishlistItems {
		qty := item.Quantity
		if qty <= 0 {
			qty = 1
		}
		if err := r.WishlistRepository.AddItem(ctx, ownWishlistID, storeID, item.Sku, qty); err != nil {
			code := model.WishlistUserInputErrorTypeUndefined
			if err.Error() == "product not found" {
				code = model.WishlistUserInputErrorTypeProductNotFound
			}
			userErrors = append(userErrors, &model.WishlistUserInputError{
				Code:    code,
				Message: err.Error(),
			})
		}
	}
	count, err := r.WishlistRepository.CountItems(ctx, ownWishlistID)
	if err != nil {
		return nil, err
	}
	wishlist := &model.Wishlist{ID: strconv.Itoa(ownWishlistID), ItemsCount: count}
	return &model.AddProductsToWishlistOutput{Wishlist: wishlist, UserErrors: userErrors}, nil
}

// RemoveProductsFromWishlist is the resolver for the removeProductsFromWishlist field.
func (r *mutationResolver) RemoveProductsFromWishlist(ctx context.Context, wishlistID string, wishlistItemsIds []string) (*model.RemoveProductsFromWishlistOutput, error) {
	customerID := middleware.GetCustomerID(ctx)
	if customerID == 0 {
		return nil, fmt.Errorf("The current customer isn't authorized.")
	}
	ownWishlistID, err := r.WishlistRepository.GetOrCreate(ctx, customerID)
	if err != nil {
		return nil, err
	}
	if wishlistID != strconv.Itoa(ownWishlistID) {
		return nil, fmt.Errorf("The current customer isn't authorized.")
	}

	var userErrors []*model.WishlistUserInputError
	var itemIDs []int
	for _, idStr := range wishlistItemsIds {
		id, err := strconv.Atoi(idStr)
		if err != nil {
			userErrors = append(userErrors, &model.WishlistUserInputError{
				Code:    model.WishlistUserInputErrorTypeUndefined,
				Message: fmt.Sprintf("invalid item id: %s", idStr),
			})
			continue
		}
		itemIDs = append(itemIDs, id)
	}

	if len(itemIDs) > 0 {
		if err := r.WishlistRepository.RemoveItems(ctx, ownWishlistID, itemIDs); err != nil {
			return nil, err
		}
	}

	count, err := r.WishlistRepository.CountItems(ctx, ownWishlistID)
	if err != nil {
		return nil, err
	}
	wishlist := &model.Wishlist{ID: strconv.Itoa(ownWishlistID), ItemsCount: count}
	return &model.RemoveProductsFromWishlistOutput{Wishlist: wishlist, UserErrors: userErrors}, nil
}

// ConfirmEmail is the resolver for the confirmEmail field.
func (r *mutationResolver) ConfirmEmail(ctx context.Context, input model.ConfirmEmailInput) (*model.CustomerOutput, error) {
	return r.CustomerService.ConfirmEmail(ctx, input)
}

// ResendConfirmationEmail is the resolver for the resendConfirmationEmail field.
func (r *mutationResolver) ResendConfirmationEmail(ctx context.Context, email string) (*bool, error) {
	result, err := r.CustomerService.ResendConfirmationEmail(ctx, email)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateCustomer is the resolver for the createCustomer field (deprecated).
func (r *mutationResolver) CreateCustomer(ctx context.Context, input model.CustomerInput) (*model.CustomerOutput, error) {
	// Convert deprecated CustomerInput to CustomerCreateInput
	createInput := model.CustomerCreateInput{
		Firstname:    derefStr(input.Firstname),
		Lastname:     derefStr(input.Lastname),
		Email:        derefStr(input.Email),
		Password:     derefStr(input.Password),
		Prefix:       input.Prefix,
		Middlename:   input.Middlename,
		Suffix:       input.Suffix,
		DateOfBirth:  coalesce(input.DateOfBirth, input.Dob),
		Taxvat:       input.Taxvat,
		Gender:       input.Gender,
		IsSubscribed: input.IsSubscribed,
	}
	return r.CustomerService.CreateCustomer(ctx, createInput)
}

// UpdateCustomer is the resolver for the updateCustomer field (deprecated).
func (r *mutationResolver) UpdateCustomer(ctx context.Context, input model.CustomerInput) (*model.CustomerOutput, error) {
	updateInput := model.CustomerUpdateInput{
		Firstname:    input.Firstname,
		Lastname:     input.Lastname,
		Middlename:   input.Middlename,
		Prefix:       input.Prefix,
		Suffix:       input.Suffix,
		DateOfBirth:  coalesce(input.DateOfBirth, input.Dob),
		Taxvat:       input.Taxvat,
		Gender:       input.Gender,
		IsSubscribed: input.IsSubscribed,
	}
	return r.CustomerService.UpdateCustomer(ctx, updateInput)
}

// Customer is the resolver for the customer field.
func (r *queryResolver) Customer(ctx context.Context) (*model.Customer, error) {
	return r.CustomerService.GetCustomer(ctx)
}

// IsEmailAvailable is the resolver for the isEmailAvailable field.
func (r *queryResolver) IsEmailAvailable(ctx context.Context, email string) (*model.IsEmailAvailableOutput, error) {
	return r.CustomerService.IsEmailAvailable(ctx, email)
}

// CustomerGroup is the resolver for the customerGroup field.
func (r *queryResolver) CustomerGroup(ctx context.Context) (*model.CustomerGroup, error) {
	return r.CustomerService.GetCustomerGroup(ctx)
}

// ItemsV2 is the resolver for the items_v2 field.
func (r *wishlistResolver) ItemsV2(ctx context.Context, obj *model.Wishlist, pageSize *int, currentPage *int) (*model.WishlistItems, error) {
	wishlistID, err := strconv.Atoi(obj.ID)
	if err != nil {
		return nil, fmt.Errorf("invalid wishlist id: %w", err)
	}
	size := 20
	if pageSize != nil && *pageSize > 0 {
		size = *pageSize
	}
	page := 1
	if currentPage != nil && *currentPage > 0 {
		page = *currentPage
	}

	items, err := r.WishlistRepository.GetItems(ctx, wishlistID, size, page)
	if err != nil {
		return nil, err
	}
	totalCount, err := r.WishlistRepository.CountItems(ctx, wishlistID)
	if err != nil {
		return nil, err
	}
	totalPages := (totalCount + size - 1) / size
	if totalPages == 0 {
		totalPages = 1
	}

	modelItems := make([]*model.WishlistItem, 0, len(items))
	for _, item := range items {
		modelItems = append(modelItems, mapWishlistItem(item))
	}
	return &model.WishlistItems{
		Items: modelItems,
		PageInfo: &model.SearchResultPageInfo{
			CurrentPage: &page,
			PageSize:    &size,
			TotalPages:  &totalPages,
		},
	}, nil
}

// Customer returns CustomerResolver implementation.
func (r *Resolver) Customer() CustomerResolver { return &customerResolver{r} }

// CustomerAddress returns CustomerAddressResolver implementation.
func (r *Resolver) CustomerAddress() CustomerAddressResolver { return &customerAddressResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Wishlist returns WishlistResolver implementation.
func (r *Resolver) Wishlist() WishlistResolver { return &wishlistResolver{r} }

type customerResolver struct{ *Resolver }
type customerAddressResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type wishlistResolver struct{ *Resolver }
